PR for solutions to six problem statement
KodeLoad/DailyKodePractice pull request #2
Opened 2024-12-30 17:26 UTC by sona15599

Kindly approve

2024-12-30 17:27 UTC, sona15599 commented
No merge conflict

2024-12-30 17:28 UTC, sona15599 commented
Has no merge conflict.

2025-01-03 07:52 UTC, OBrutus requested changes

2025-01-03 07:52 UTC, OBrutus commented on .vscode/c_cpp_properties.json
remove .vscode dir

2025-01-03 07:52 UTC, OBrutus commented on Leetcode/75.SortColors/cpp/TwoPointerSolution.exe
remove this binary

2025-01-03 07:52 UTC, OBrutus commented on Leetcode/DeleteNodeInTheLinkedList/Solution.cpp
move this to cpp dir

2025-01-03 07:52 UTC, OBrutus commented on Leetcode/LinearTimeApproach.cpp
move this to cpp dir

2025-01-03 07:55 UTC, OBrutus commented
could you add these 
```
*.exe
.vscode/
```

to `.gitignore`

2025-01-11 14:35 UTC, merged